# Generated by Django 2.0.3 on 2019-03-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_dijkstramodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dijkstramodel',
            name='reg5',
        ),
    ]
