# Generated by Django 2.0.3 on 2019-03-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_remove_dijkstramodel_reg5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dijkstramodel',
            name='reg1',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='dijkstramodel',
            name='reg2',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='dijkstramodel',
            name='reg3',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='dijkstramodel',
            name='reg4',
            field=models.IntegerField(max_length=15),
        ),
    ]
