# Generated by Django 2.0.3 on 2019-03-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20190325_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dijkstramodel',
            name='reg1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dijkstramodel',
            name='reg2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dijkstramodel',
            name='reg3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dijkstramodel',
            name='reg4',
            field=models.IntegerField(),
        ),
    ]
