# Generated by Django 2.0.3 on 2019-03-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20190327_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dijkstramodel',
            name='reg2',
        ),
        migrations.RemoveField(
            model_name='dijkstramodel',
            name='reg3',
        ),
        migrations.AlterModelTable(
            name='dijkstramodel',
            table='regional2',
        ),
    ]
